INSERT INTO `teams`
(`id`, `name`, `acronym`, `primary_color`, `secondary_color`, `league_id`, `conference_id`, `city`, `description`, `created_at`, `updated_at`)
VALUES
-- Conference 1 (NCR) - Metro Manila
(1, 'Lions', 'LIO', '0076B6', 'B0B7BC', 1, 1, 'Quezon City', 'NCR predators roaring with Commonwealth pride', NOW(), NOW()), -- Detroit Lions (NFL)
(2, 'Tigers', 'TIG', '0C2340', 'FA4616', 1, 1, 'Manila', 'Capital wildcats with Intramuros strength', NOW(), NOW()), -- Detroit Tigers (MLB)
(3, 'Bears', 'BEA', '0B162A', 'C83803', 1, 1, 'Makati', 'Financial jungle brutes with skyscraper grit', NOW(), NOW()), -- Chicago Bears (NFL)
(4, 'Wolves', 'WOL', '0C2340', 'C4CED4', 1, 1, 'Taguig', 'Bonifacio hunters with elite urban tactics', NOW(), NOW()), -- Minnesota Timberwolves (NBA)
(5, 'Eagles', 'EAG', '004C54', 'A5ACAF', 1, 1, 'Pasig', 'Ortigas raptors soaring above traffic chaos', NOW(), NOW()), -- Philadelphia Eagles (NFL)
(6, 'Falcons', 'FAL', 'A71930', '000000', 1, 1, 'Caloocan', 'North Metro aerial attackers with steel resolve', NOW(), NOW()), -- Atlanta Falcons (NFL)
(7, 'Hawks', 'HAW', 'E03A3E', '26282A', 1, 1, 'Parañaque', 'Southern sky hunters gliding past the bay breeze', NOW(), NOW()), -- Atlanta Hawks (NBA)
(8, 'Panthers', 'PAN', '0085CA', '101820', 1, 1, 'Mandaluyong', 'Urban jungle prowlers with central bite', NOW(), NOW()), -- Carolina Panthers (NFL)
(9, 'Athletics', 'ATH', '003831', 'EFB21E', 1, 1, 'San Juan', 'Tiny city titans running with green-hearted hustle', NOW(), NOW()), -- Oakland Athletics (MLB)
(10, 'Vipers', 'VIP', '1D428A', 'C8102E', 1, 1, 'Pasay', 'Bayfront strikers with terminal velocity', NOW(), NOW()), -- Detroit Pistons (NBA colors)
(11, 'Jaguars', 'JAG', '006778', '9F7925', 1, 1, 'Las Piñas', 'South Metro prowlers with bamboo toughness', NOW(), NOW()), -- Jacksonville Jaguars (NFL)
(12, 'Dolphins', 'DOL', '008E97', 'F58220', 1, 1, 'Valenzuela', 'Industrial sea acrobats with steel nerve', NOW(), NOW()), -- Miami Dolphins (NFL)
(13, 'Rockets', 'RCK', 'CE1141', 'C4CED4', 1, 1, 'Navotas', 'Fishing port launchers with harbor blast power', NOW(), NOW()), -- Houston Rockets (NBA)
(14, 'Braves', 'BRV', '13274F', 'CE1141', 1, 1, 'Malabon', 'Northern warriors with flood-tested bravery', NOW(), NOW()), -- Atlanta Braves (MLB)
(15, 'Blazers', 'BLZ', 'E03A3E', 'B6AFA9', 1, 1, 'Marikina', 'Shoe capital torches sprinting with artisan fire', NOW(), NOW()), -- Portland Trail Blazers (NBA)
(16, 'Kings', 'KIN', '5A2D81', '000000', 1, 1, 'Muntinlupa', 'Southern monarchs guarding the lakeside throne', NOW(), NOW()), -- Sacramento Kings (NBA)

-- Conference 2 (North) - Luzon
(17, 'Titans', 'TIT', '0C2340', 'C8102E', 1, 2, 'Baguio', 'Highland giants crushing foes with pine-fresh dominance', NOW(), NOW()), -- Tennessee Titans (NFL)
(18, 'Spartans', 'SPA', '18453B', '000000', 1, 2, 'Laoag', 'Ilocano warriors standing tall with windmill might', NOW(), NOW()), -- Michigan State Spartans (NCAA)
(19, 'Trojans', 'TRO', '990000', '101820', 1, 2, 'Tarlac City', 'Central Luzon tacticians breaking lines with shield and speed', NOW(), NOW()), -- USC Trojans (NCAA)
(20, 'Saints', 'SNT', '101820', 'D3BC8D', 1, 2, 'Vigan', 'Heritage believers with cobblestone resilience', NOW(), NOW()), -- New Orleans Saints (NFL)
(21, 'Aliens', 'ALN', '1C2526', '330072', 1, 2, 'Olongapo', 'Subic spacewalkers beaming with naval discipline', NOW(), NOW()), -- Las Vegas Aces (NBA colors)
(22, 'Leopards', 'LEO', 'C8102E', '041E42', 1, 2, 'Legazpi', 'Mayon hunters striking with volcanic elegance', NOW(), NOW()), -- Cincinnati Bengals (NFL colors)
(23, 'Sabertooths', 'SAB', '041E42', '000000', 1, 2, 'Lucena', 'Quezon predators slicing through coconut groves', NOW(), NOW()), -- Buffalo Sabres (NHL)
(24, 'Spiders', 'SPD', 'CE1141', '003087', 1, 2, 'Nueva Ecija', 'Nueva Ecija web-weavers with farmer precision', NOW(), NOW()), -- San Francisco Giants (MLB colors)
(25, 'Vikings', 'VIK', '4F2683', '000000', 1, 2, 'Pampanga', 'Pampanga raiders with culinary carnage', NOW(), NOW()), -- Minnesota Vikings (NFL)
(26, 'Crows', 'CRW', '241F20', '000000', 1, 2, 'Batangas City', 'Heritage scavengers with refinery strength', NOW(), NOW()), -- Baltimore Ravens (NFL inspiration)
(27, 'Royals', 'RYL', '004687', '17457C', 1, 2, 'Naga', 'Bicolano kings with fiery river spirit', NOW(), NOW()), -- Kansas City Royals (MLB)
(28, 'Thunders', 'THN', '007AC1', 'EF3B24', 1, 2, 'Mindoro', 'Oriental lightning strikers with island storm bursts', NOW(), NOW()), -- Oklahoma City Thunder (NBA)
(29, 'Warriors', 'WAR', '006BB6', '000000', 1, 2, 'Kalinga', 'Kalinga fighters charging with highland pride', NOW(), NOW()), -- Golden State Warriors (NBA)
(30, 'Hellhounds', 'HH', '1D428A', 'C8102E', 1, 2, 'Sorsogon', 'Bicolano guardians unleashing underworld ferocity', NOW(), NOW()), -- Detroit Pistons (NBA)
(31, 'Red Fox', 'RF', '5B2B2F', 'FFB612', 1, 2, 'Tuguegarao', 'Cagayan tricksters darting through valley winds', NOW(), NOW()), -- Washington Commanders (NFL colors)
(32, 'Cougars', 'CGR', '0C2C56', '005C5C', 1, 2, 'Puerto Princesa', 'Palawan prowlers guarding nature’s sanctuary', NOW(), NOW()), -- Seattle Mariners (MLB)

-- Conference 3 (Visayas)
(33, 'Waves', 'WAV', '002244', '69BE28', 1, 3, 'Cebu City', 'Queen City surfers riding Central Visayan currents', NOW(), NOW()), -- Seattle Seahawks (NFL colors)
(34, 'Predators', 'PRD', '041E42', '000000', 1, 3, 'Iloilo City', 'Dinagyang hunters feasting on heritage and heart', NOW(), NOW()), -- Nashville Predators (NHL)
(35, 'Trilogy', 'TRI', 'C8102E', '002B5C', 1, 3, 'Bacolod', 'MassKara trio lighting up with sugar-fueled rhythm', NOW(), NOW()), -- Miami Heat (NBA colors)
(36, 'Monarchs', 'MON', '5A2D81', '000000', 1, 3, 'Tacloban', 'Leyte royalty rising from storm-swept history', NOW(), NOW()), -- Sacramento Kings (NBA alternate)
(37, 'Krakens', 'KRK', '001628', 'E9072B', 1, 3, 'Dumaguete', 'Sea beasts breaching with university intellect', NOW(), NOW()), -- Seattle Kraken (NHL)
(38, 'Jets', 'JET', '003F2D', '000000', 1, 3, 'Tagbilaran', 'Bohol launchers soaring over Chocolate Hills', NOW(), NOW()), -- New York Jets (NFL)
(39, 'Northern Stars', 'NS', '006847', '000000', 1, 3, 'Roxas City', 'Capiz brilliance shining beyond seafood shores', NOW(), NOW()), -- Dallas Stars (NHL)
(40, 'Ninjas', 'NIN', '000000', 'C4CED4', 1, 3, 'Ormoc', 'Leyte shadows striking silently from the west', NOW(), NOW()), -- San Antonio Spurs (NBA inspiration)
(41, 'Dragons', 'DRA', '1D1160', 'E56020', 1, 3, 'Kalibo', 'Ati-atihan serpents blazing through Panay winds', NOW(), NOW()), -- Los Angeles Lakers (NBA colors)
(42, 'Phoenix', 'PHO', '1D1160', 'E56020', 1, 3, 'Catarman', 'Northern Samar flames rising from island ashes', NOW(), NOW()), -- Phoenix Suns (NBA)
(43, 'Sharks', 'SHA', '006D75', '000000', 1, 3, 'San Jose', 'Antique predators circling with quiet fury', NOW(), NOW()), -- San Jose Sharks (NHL)
(44, 'Giants', 'GNT', '0B2265', 'A71930', 1, 3, 'Baybay', 'Southern Leyte titans grounded in historic soil', NOW(), NOW()), -- New York Giants (NFL)
(45, 'Fire', 'FRE', '98002E', '000000', 1, 3, 'Maasin', 'Fiery defenders igniting island battles', NOW(), NOW()), -- Chicago Fire (MLS)
(46, 'Patriots', 'PAT', '002244', 'C8102E', 1, 3, 'Cadiz', 'Negros patriots blazing with sugarland pride', NOW(), NOW()), -- New England Patriots (NFL)
(47, 'Aces', 'ACE', 'B4975A', '000000', 1, 3, 'Bogo', 'Northern Cebu elites with coastal confidence', NOW(), NOW()), -- Las Vegas Aces (WNBA)
(48, 'Monsters', 'MNT', '6F263D', 'FDBB30', 1, 3, 'Guihulngan', 'Mountain beasts roaring with resilience', NOW(), NOW()), -- Cleveland Monsters (AHL)

-- Conference 4 (Mindanao)
(49, 'Pirates', 'PIR', 'D50A0A', '34302B', 1, 4, 'Davao City', 'King City raiders sailing with durian dominance', NOW(), NOW()), -- Pittsburgh Pirates (MLB)
(50, 'Scorpions', 'SCR', '1C2526', '330072', 1, 4, 'Zamboanga', 'Chavacano stingers dancing to Latin precision', NOW(), NOW()), -- Charlotte Hornets (NBA colors)
(51, 'Enemies', 'ENM', '101820', 'FFB612', 1, 4, 'Cagayan de Oro', 'Golden rivals armed with friendship fury', NOW(), NOW()), -- Pittsburgh Steelers (NFL colors)
(52, 'Reapers', 'RPR', '241F20', '000000', 1, 4, 'General Santos', 'Tuna town harvesters with knockout menace', NOW(), NOW()), -- Las Vegas Raiders (NFL inspiration)
(53, 'Raiders', 'RAI', '000000', 'C4CED4', 1, 4, 'Butuan', 'Caraga marauders with ancient balangay speed', NOW(), NOW()), -- Las Vegas Raiders (NFL)
(54, 'Whales', 'WH', '005C5C', '000000', 1, 4, 'Tagum', 'Davao del Norte giants gliding through palm rows', NOW(), NOW()), -- Miami Marlins (MLB colors)
(55, 'Poseidons', 'POS', '006D75', 'E9072B', 1, 4, 'Surigao City', 'Sea gods ruling tides with mining muscle', NOW(), NOW()), -- San Diego Padres (MLB colors)
(56, 'Cyclones', 'CYC', '4B0082', 'FF4500', 1, 4, 'Cotabato City', 'River city storms with Maguindanao force', NOW(), NOW()), -- Brooklyn Nets (NBA inspiration)
(57, 'Force', 'FRC', '006BB6', 'ED174C', 1, 4, 'Pagadian', 'Zamboanga swirl charging with hilltop speed', NOW(), NOW()), -- Philadelphia 76ers (NBA)
(58, 'Astronauts', 'AST', '004687', '17457C', 1, 4, 'Marawi', 'Lanao explorers orbiting in rebuilt glory', NOW(), NOW()), -- Houston Astros (MLB)
(59, 'Demons', 'DMN', '0B162A', 'C83803', 1, 4, 'Iligan City', 'Waterfall phantoms striking from hydro heights', NOW(), NOW()), -- Chicago Bears (NFL colors)
(60, 'Devils', 'DVL', 'D50A0A', '34302B', 1, 4, 'Malaybalay', 'Bukidnon tempters rising from pine-kissed plateaus', NOW(), NOW()), -- New Jersey Devils (NHL)
(61, 'Bulldogs', 'BD', '003087', '000000', 1, 4, 'Kidapawan', 'Volcano guards bulldozing with hot spring grit', NOW(), NOW()), -- Georgia Bulldogs (NCAA)
(62, 'Hornets', 'HRN', '1C2526', '330072', 1, 4, 'Digos', 'Southern stingers buzzing past banana lines', NOW(), NOW()), -- Charlotte Hornets (NBA)
(63, 'Rebels', 'RBL', 'EF0107', '023474', 1, 4, 'Panabo City', 'Agri city insurgents defending with fearless crops', NOW(), NOW()), -- UNLV Rebels (NCAA)
(64, 'Owls', 'OWL', '0C2340', 'C8102E', 1, 4, 'Tandag', 'Midnight wisdom flying from the coastal dark', NOW(), NOW()); -- Temple Owls (NCAA)