INSERT INTO `teams` 
(`id`, `name`, `acronym`, `primary_color`, `secondary_color`, `league_id`, `conference_id`, `city`, `description`, `created_at`, `updated_at`) 
VALUES
-- Conference 1 (NCR) - NFL/NCAA Color Schemes
(1, 'Lions', 'LIO', '0072CE', 'FFB300', 1, 1, 'Quezon City', 'NCR predators roaring with Commonwealth pride', NOW(), NOW()),
(2, 'Tigers', 'TIG', 'FB4F14', '2E7D32', 1, 1, 'Manila', 'Capital wildcats with Intramuros strength', NOW(), NOW()),
(3, 'Bears', 'BEA', '0B162A', 'FFCA28', 1, 1, 'Makati', 'Financial jungle brutes with skyscraper grit', NOW(), NOW()),
(4, 'Wolves', 'WOL', '4E342E', '00A1D6', 1, 1, 'Taguig', 'Bonifacio hunters with elite urban tactics', NOW(), NOW()),
(5, 'Eagles', 'EAG', '004AAD', 'F5F5F5', 1, 1, 'Pasig', 'Ortigas raptors soaring above traffic chaos', NOW(), NOW()),
(6, 'Falcons', 'FAL', 'D32F2F', '78909C', 1, 1, 'Caloocan', 'North Metro aerial attackers with steel resolve', NOW(), NOW()),
(7, 'Hawks', 'HAW', 'B71C1C', 'FFD54F', 1, 1, 'Parañaque', 'Southern sky hunters gliding past the bay breeze', NOW(), NOW()),
(8, 'Panthers', 'PAN', '2E8B57', 'AB47BC', 1, 1, 'Mandaluyong', 'Urban jungle prowlers with central bite', NOW(), NOW()),
(9, 'Athletics', 'ATH', '66BB6A', '4E342E', 1, 1, 'San Juan', 'Tiny city titans running with green-hearted hustle', NOW(), NOW()),
(10, 'Vipers', 'VIP', '7B1FA2', 'FF6F00', 1, 1, 'Pasay', 'Bayfront strikers with terminal velocity', NOW(), NOW()),
(11, 'Jaguars', 'JAG', '00897B', 'D81B60', 1, 1, 'Las Piñas', 'South Metro prowlers with bamboo toughness', NOW(), NOW()),
(12, 'Dolphins', 'DOL', '00A1D6', 'F06292', 1, 1, 'Valenzuela', 'Industrial sea acrobats with steel nerve', NOW(), NOW()),
(13, 'Rockets', 'RCK', 'C62828', 'A5D6A7', 1, 1, 'Navotas', 'Fishing port launchers with harbor blast power', NOW(), NOW()),
(14, 'Braves', 'BRV', '3E2723', '66BB6A', 1, 1, 'Malabon', 'Northern warriors with flood-tested bravery', NOW(), NOW()),
(15, 'Blazers', 'BLZ', 'FF6F00', '004AAD', 1, 1, 'Marikina', 'Shoe capital torches sprinting with artisan fire', NOW(), NOW()),
(16, 'Kings', 'KIN', '512DA8', 'FFD54F', 1, 1, 'Muntinlupa', 'Southern monarchs guarding the lakeside throne', NOW(), NOW()),

-- Conference 2 (North) - NCAA Focus
(17, 'Titans', 'TIT', '01579B', 'FFB300', 1, 2, 'Baguio', 'Highland giants crushing foes with pine-fresh dominance', NOW(), NOW()),
(18, 'Spartans', 'SPA', '1B5E20', '01579B', 1, 2, 'Laoag', 'Ilocano warriors standing tall with windmill might', NOW(), NOW()),
(19, 'Trojans', 'TRO', 'B71C1C', 'FFCA28', 1, 2, 'Tarlac City', 'Central Luzon tacticians breaking lines with shield and speed', NOW(), NOW()),
(20, 'Saints', 'SNT', 'FDD835', '3E2723', 1, 2, 'Vigan', 'Heritage believers with cobblestone resilience', NOW(), NOW()),
(21, 'Aliens', 'ALN', '00C853', '7B1FA2', 1, 2, 'Olongapo', 'Subic spacewalkers beaming with naval discipline', NOW(), NOW()),
(22, 'Leopards', 'LEO', '6D4C41', '00A1D6', 1, 2, 'Legazpi', 'Mayon hunters striking with volcanic elegance', NOW(), NOW()),
(23, 'Sabertooths', 'SAB', '0288D1', 'F06292', 1, 2, 'Lucena', 'Quezon predators slicing through coconut groves', NOW(), NOW()),
(24, 'Spiders', 'SPD', '283593', 'FF6F00', 1, 2, 'Nueva Ecija', 'Nueva Ecija web-weavers with farmer precision', NOW(), NOW()),
(25, 'Vikings', 'VIK', '7B1FA2', 'FFD54F', 1, 2, 'Pampanga', 'Pampanga raiders with culinary carnage', NOW(), NOW()),
(26, 'Crows', 'CRW', '21F06292', '66BB6A', 1, 2, 'Batangas City', 'Heritage scavengers with refinery strength', NOW(), NOW()),
(27, 'Royals', 'RYL', '0277BD', 'FFB300', 1, 2, 'Naga', 'Bicolano kings with fiery river spirit', NOW(), NOW()),
(28, 'Thunders', 'THN', '0288D1', 'D81B60', 1, 2, 'Mindoro', 'Oriental lightning strikers with island storm bursts', NOW(), NOW()),
(29, 'Warriors', 'WAR', '1565C0', 'FFCA28', 1, 2, 'Kalinga', 'Kalinga fighters charging with highland pride', NOW(), NOW()),
(30, 'Hellhounds', 'HH', 'B71C1C', '78909C', 1, 2, 'Sorsogon', 'Bicolano guardians unleashing underworld ferocity', NOW(), NOW()),
(31, 'Red Fox', 'RF', 'D32F2F', 'A5D6A7', 1, 2, 'Tuguegarao', 'Cagayan tricksters darting through valley winds', NOW(), NOW()),
(32, 'Cougars', 'CGR', '8D6E63', '00A1D6', 1, 2, 'Puerto Princesa', 'Palawan prowlers guarding nature’s sanctuary', NOW(), NOW()),

-- Conference 3 (Visayas) - Mixed League Styles
(33, 'Waves', 'WAV', '00897B', 'FFCA28', 1, 3, 'Cebu City', 'Queen City surfers riding Central Visayan currents', NOW(), NOW()),
(34, 'Predators', 'PRD', '01579B', 'F06292', 1, 3, 'Iloilo City', 'Dinagyang hunters feasting on heritage and heart', NOW(), NOW()),
(35, 'Trilogy', 'TRI', '78909C', 'FFB300', 1, 3, 'Bacolod', 'MassKara trio lighting up with sugar-fueled rhythm', NOW(), NOW()),
(36, 'Monarchs', 'MON', '512DA8', 'F5F5F5', 1, 3, 'Tacloban', 'Leyte royalty rising from storm-swept history', NOW(), NOW()),
(37, 'Krakens', 'KRK', '006064', 'FF6F00', 1, 3, 'Dumaguete', 'Sea beasts breaching with university intellect', NOW(), NOW()),
(38, 'Jets', 'JET', '2E7D32', 'D81B60', 1, 3, 'Tagbilaran', 'Bohol launchers soaring over Chocolate Hills', NOW(), NOW()),
(39, 'Northern Stars', 'NS', '0288D1', 'FFD54F', 1, 3, 'Roxas City', 'Capiz brilliance shining beyond seafood shores', NOW(), NOW()),
(40, 'Ninjas', 'NIN', '212121', 'F06292', 1, 3, 'Ormoc', 'Leyte shadows striking silently from the west', NOW(), NOW()),
(41, 'Dragons', 'DRA', 'FF6F00', '2E8B57', 1, 3, 'Kalibo', 'Ati-atihan serpents blazing through Panay winds', NOW(), NOW()),
(42, 'Phoenix', 'PHO', '6D4C41', 'A5D6A7', 1, 3, 'Catarman', 'Northern Samar flames rising from island ashes', NOW(), NOW()),
(43, 'Sharks', 'SHA', '00A1D6', '78909C', 1, 3, 'San Jose', 'Antique predators circling with quiet fury', NOW(), NOW()),
(44, 'Giants', 'GNT', '01579B', 'FFD54F', 1, 3, 'Baybay', 'Southern Leyte titans grounded in historic soil', NOW(), NOW()),
(45, 'Fire', 'FRE', 'C62828', '66BB6A', 1, 3, 'Maasin', 'Fiery defenders igniting island battles', NOW(), NOW()),
(46, 'Patriots', 'PAT', '3E2723', '00A1D6', 1, 3, 'Cadiz', 'Negros patriots blazing with sugarland pride', NOW(), NOW()),
(47, 'Aces', 'ACE', 'D32F2F', 'F5F5F5', 1, 3, 'Bogo', 'Northern Cebu elites with coastal confidence', NOW(), NOW()),
(48, 'Monsters', 'MNT', '7B1FA2', 'FFCA28', 1, 3, 'Guihulngan', 'Mountain beasts roaring with resilience', NOW(), NOW()),

-- Conference 4 (Mindanao) - Bold Color Schemes
(49, 'Pirates', 'PIR', '006064', 'FFD54F', 1, 4, 'Davao City', 'King City raiders sailing with durian dominance', NOW(), NOW()),
(50, 'Scorpions', 'SCR', 'FFB300', '2E8B57', 1, 4, 'Zamboanga', 'Chavacano stingers dancing to Latin precision', NOW(), NOW()),
(51, 'Enemies', 'ENM', '1B5E20', 'F06292', 1, 4, 'Cagayan de Oro', 'Golden rivals armed with friendship fury', NOW(), NOW()),
(52, 'Reapers', 'RPR', '212121', 'FF6F00', 1, 4, 'General Santos', 'Tuna town harvesters with knockout menace', NOW(), NOW()),
(53, 'Raiders', 'RAI', '78909C', 'D32F2F', 1, 4, 'Butuan', 'Caraga marauders with ancient balangay speed', NOW(), NOW()),
(54, 'Whales', 'WH', '0288D1', 'A5D6A7', 1, 4, 'Tagum', 'Davao del Norte giants gliding through palm rows', NOW(), NOW()),
(55, 'Poseidons', 'POS', '00897B', 'FFD54F', 1, 4, 'Surigiao City', 'Sea gods ruling tides with mining muscle', NOW(), NOW()),
(56, 'Cyclones', 'CYC', '512DA8', 'FFCA28', 1, 4, 'Cotabato City', 'River city storms with Maguindanao force', NOW(), NOW()),
(57, 'Force', 'FRC', '01579B', '78909C', 1, 4, 'Pagadian', 'Zamboanga swirl charging with hilltop speed', NOW(), NOW()),
(58, 'Astronauts', 'AST', 'FF6F00', 'A5D6A7', 1, 4, 'Marawi', 'Lanao explorers orbiting in rebuilt glory', NOW(), NOW()),
(59, 'Demons', 'DMN', '6D4C41', '00A1D6', 1, 4, 'Iligan City', 'Waterfall phantoms striking from hydro heights', NOW(), NOW()),
(60, 'Devils', 'DVL', 'C62828', '212121', 1, 4, 'Malaybalay', 'Bukidnon tempters rising from pine-kissed plateaus', NOW(), NOW()),
(61, 'Bulldogs', 'BD', '3E2723', 'FFCA28', 1, 4, 'Kidapawan', 'Volcano guards bulldozing with hot spring grit', NOW(), NOW()),
(62, 'Hornets', 'HRN', 'FDD835', '2E8B57', 1, 4, 'Digos', 'Southern stingers buzzing past banana lines', NOW(), NOW()),
(63, 'Rebels', 'RBL', 'B71C1C', 'A5D6A7', 1, 4, 'Panabo City', 'Agri city insurgents defending with fearless crops', NOW(), NOW()),
(64, 'Owls', 'OWL', '8D6E63', 'F06292', 1, 4, 'Tandag', 'Midnight wisdom flying from the coastal dark', NOW(), NOW());