    CREATE OR REPLACE TABLE `schedule_view_snapshot` (
    `id` bigint(20) UNSIGNED ,
    `game_id` varchar(255) ,
    `game_number` varchar(255) ,
    `round` varchar(255) ,
    `season_id` varchar(255) ,
    `conference_id` varchar(255) ,
    `series_id` varchar(255) ,
    `series_number` int(20) ,
    `home_id` int(20) ,
    `home_score` int(20) ,
    `away_id` int(20) ,
    `away_score` int(20) ,
    `winner_id` int(20) ,
    `status` int(20) ,
    `created_at` varchar(255) ,
    `updated_at` varchar(255) ,
    `game_number_formatted` int(20) ,
    `series_id_number` varchar(255) ,
    `home_team_name` varchar(255) ,
    `away_team_name` varchar(255) ,
    `home_primary_color` varchar(255) ,
    `away_primary_color` varchar(255) ,
    `home_secondary_color` varchar(255) ,
    `away_secondary_color` varchar(255) ,
    `home_team_city` varchar(255) ,
    `away_team_city` varchar(255) ,
    `season_name` varchar(255) ,
    `league_name` varchar(255) ,
    `league_type` int(20) ,
    `winning_name` varchar(255) ,
    `winning_city` varchar(255) 
    )