CREATE TABLE standings_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id BIGINT UNSIGNED NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    team_city VARCHAR(100) NOT NULL,
    primary_color VARCHAR(7) NULL,
    secondary_color VARCHAR(7) NULL,
    team_acronym VARCHAR(10) NOT NULL,
    conference_id BIGINT UNSIGNED NOT NULL,
    conference_name VARCHAR(100) NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    wins INT UNSIGNED NOT NULL DEFAULT 0,
    losses INT UNSIGNED NOT NULL DEFAULT 0,
    total_home_score INT UNSIGNED NOT NULL DEFAULT 0,
    total_away_score INT UNSIGNED NOT NULL DEFAULT 0,
    home_ppg DECIMAL(5,2) NULL,
    away_ppg DECIMAL(5,2) NULL,
    score_difference INT NOT NULL DEFAULT 0,
    conference_rank INT UNSIGNED NOT NULL,
    overall_rank INT UNSIGNED NOT NULL,
    is_defending_champion TINYINT(1) NOT NULL DEFAULT 0,
    chemistry VARCHAR(50) NULL,
    last_playoff_season_name VARCHAR(100) NOT NULL DEFAULT '',
    playoff_appearances INT UNSIGNED NOT NULL DEFAULT 0,
    finals_appearances INT UNSIGNED NOT NULL DEFAULT 0,
    conference_finals_appearances INT UNSIGNED NOT NULL DEFAULT 0,
    conference_championships INT UNSIGNED NOT NULL DEFAULT 0,
    championships INT UNSIGNED NOT NULL DEFAULT 0,
    streak_status VARCHAR(10) NULL,
    last_5_games VARCHAR(5) NOT NULL DEFAULT '',
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_team_id (team_id),
    INDEX idx_conference_id (conference_id),
    INDEX idx_season_id (season_id)
)