CREATE TABLE storylines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    season_id BIGINT NOT NULL,
    storyline TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);