CREATE TABLE `team_season_info` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL,
  `conference_id` BIGINT UNSIGNED NOT NULL,
  `coach_id` BIGINT UNSIGNED NOT NULL,
  `coach_iq` INT UNSIGNED NOT NULL, 
  `chemistry` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL
)
