INSERT INTO `teams` (
    `id`, `name`, `acronym`, `primary_color`, `secondary_color`, `league_id`, `conference_id`, `city`, `description`, `created_at`, `updated_at`
) VALUES
-- Conference 1 (North Luzon)
(1,  'Lions',     'LIO', '0076B6', 'B0B7BC', 1, 1, 'Quezon City',     'Roar with Pride!',                          NOW(), NOW()),
(2,  'Tigers',    'TIG', '0C2340', 'FA4616', 1, 1, 'Manila',          'Claw the Capital!',                         NOW(), NOW()),
(3,  'Bears',     'BEA', '0B162A', 'C83803', 1, 1, 'Makati',          'Grip the Victory!',                         NOW(), NOW()),
(4,  'Wolves',    'WOL', '236192', 'C4CED4', 1, 1, 'Taguig',          'Hunt as One!',                              NOW(), NOW()),
(5,  'Eagles',    'EAG', '004C54', 'A5ACAF', 1, 1, 'Pasig',           'Soar to Glory!',                            NOW(), NOW()),
(6,  'Falcons',   'FAL', 'A71930', '101820', 1, 1, 'Caloocan',        'Strike from Above!',                        NOW(), NOW()),
(7,  'Hawks',     'HAW', 'E03A3E', 'FDB927', 1, 1, 'Parañaque',       'Swoop to Conquer!',                         NOW(), NOW()),
(8,  'Panthers',  'PAN', '0085CA', '101820', 1, 1, 'Mandaluyong',     'Prowl with Power!',                         NOW(), NOW()),
(9,  'Athletics', 'ATH', '003831', 'EFB21E', 1, 1, 'San Juan',        'Run to Triumph!',                           NOW(), NOW()),
(10, 'Vipers',    'VIP', '1D428A', 'C8102E', 1, 1, 'Pasay',           'Strike with Venom!',                        NOW(), NOW()),
(11, 'Jaguars',   'JAG', '006778', '9F7925', 1, 1, 'Las Piñas',       'Leap to Dominate!',                         NOW(), NOW()),
(12, 'Dolphins',  'DOL', '008E97', 'F58220', 1, 1, 'Valenzuela',      'Dive to Victory!',                          NOW(), NOW()),
(13, 'Rockets',   'RCK', 'CE1141', 'C4CED4', 1, 1, 'Navotas',         'Launch to Greatness!',                      NOW(), NOW()),
(14, 'Braves',    'BRV', '13274F', 'CE1141', 1, 1, 'Malabon',         'Charge with Courage!',                      NOW(), NOW()),
(15, 'Blazers',   'BLZ', 'E03A3E', '000000', 1, 1, 'Marikina',        'Blaze the Trail!',                          NOW(), NOW()),
(16, 'Kings',     'KIN', '5A2D81', '63727A', 1, 1, 'Muntinlupa',      'Rule the Court!',                           NOW(), NOW()),
(17, 'Titans',    'TIT', '002244', 'C60C30', 1, 1, 'Baguio',          'Crush with Might!',                         NOW(), NOW()),
(18, 'Spartans',  'SPA', '18453B', 'A3A3A3', 1, 1, 'Laoag',           'Fight with Honor!',                         NOW(), NOW()),
(19, 'Trojans',   'TRO', '990000', 'FFC72C', 1, 1, 'Tarlac City',     'Conquer the Field!',                        NOW(), NOW()),
(20, 'Saints',    'SNT', '101820', 'D3BC8D', 1, 1, 'Vigan',           'March to Salvation!',                       NOW(), NOW()),
(29, 'Warriors',  'WAR', '1D428A', 'FDB927', 1, 1, 'Kalinga',         'Battle to Win!',                            NOW(), NOW()),
(31, 'Red Fox',   'RF',  '5B2B2F', 'FFB612', 1, 1, 'Tuguegarao',      'Outfox the Foe!',                           NOW(), NOW()),
(67, 'Rascals',   'RSC', 'FFCC00', 'FF5733', 1, 1, 'West Manila',     'Hustle with Heart!',                        NOW(), NOW()),
(70, 'Sonics',    'SNC', '1E90FF', '003366', 1, 1, 'La Union',        'Ride the Rhythm!',                          NOW(), NOW()),
-- Conference 2 (South Luzon)
(21, 'Aliens',    'ALN', '1C2526', '6F2DA8', 1, 2, 'Olongapo',        'Invade the Game!',                          NOW(), NOW()),
(22, 'Leopards',  'LEO', 'C8102E', 'FFD100', 1, 2, 'Legazpi',         'Stalk the Win!',                            NOW(), NOW()),
(23, 'Sabertooths', 'SAB', '00205B', 'A2AAAD', 1, 2, 'Lucena',        'Slash to Victory!',                         NOW(), NOW()),
(24, 'Spiders',   'SPD', 'CE1141', '1D428A', 1, 2, 'Nueva Ecija',     'Weave the Win!',                            NOW(), NOW()),
(25, 'Vikings',   'VIK', '4F2683', 'FFC62F', 1, 2, 'Pampanga',        'Raid the Glory!',                           NOW(), NOW()),
(26, 'Crows',     'CRW', '241F20', 'A2AAAD', 1, 2, 'Batangas City',   'Caw for Conquest!',                         NOW(), NOW()),
(27, 'Royals',    'RYL', '004687', 'C5B358', 1, 2, 'Naga',            'Reign Supreme!',                            NOW(), NOW()),
(28, 'Thunders',  'THN', '007AC1', 'F05133', 1, 2, 'Mindoro',         'Strike with Storm!',                        NOW(), NOW()),
(30, 'Hellhounds', 'HH', '1D1D1D', 'FF0000', 1, 2, 'Sorsogon',        'Unleash the Fury!',                         NOW(), NOW()),
(32, 'Cougars',   'CGR', '003B4D', '007C92', 1, 2, 'Puerto Princesa', 'Pounce to Power!',                          NOW(), NOW()),
(65, 'Angels',    'ACA', 'FFCC00', '003366', 1, 2, 'Angeles City',    'Soar with Grace!',                          NOW(), NOW()),
(66, 'Knights',   'KNT', '333399', 'CCCCCC', 1, 2, 'Malolos',         'Charge with Valor!',                        NOW(), NOW()),
(68, 'Stingers',  'PTS', 'FFD700', '1A1A1A', 1, 2, 'Pateros',         'Small Team. Big Sting.',                     NOW(), NOW()),
(69, 'Ghosts',    'GHS', 'A9A9A9', '777777', 1, 2, 'Bataan',          'Haunt the Court!',                          NOW(), NOW()),
(71, 'Kryptonites', 'KRY', '3B8C3A', 'FFD700', 1, 2, 'Bulacan',       'Shine Unstoppable!',                        NOW(), NOW()),
(72, 'Red Arrows', 'IRA', '8B0000', 'FFD700', 1, 2, 'Imus',       'Bleed for the Mark!',                       NOW(), NOW()),
-- Conference 3 (Visayas)
(33, 'Waves',     'WAV', '002244', 'EFD9A1', 1, 3, 'Cebu City',       'Ride the Surge!',                           NOW(), NOW()),
(34, 'Predators', 'PRD', '041E42', 'FFB81C', 1, 3, 'Iloilo City',     'Hunt the Glory!',                           NOW(), NOW()),
(35, 'Trilogy',   'TRI', 'C8102E', '002B5C', 1, 3, 'Bacolod',         'Trio of Triumph!',                          NOW(), NOW()),
(36, 'Monarchs',  'MON', '5A2D81', 'D6AF36', 1, 3, 'Tacloban',        'Rule the Realm!',                           NOW(), NOW()),
(37, 'Krakens',   'KRK', '001628', '99D9D9', 1, 3, 'Dumaguete',       'Unleash the Deep!',                         NOW(), NOW()),
(38, 'Jets',      'JET', '003F2D', '78B833', 1, 3, 'Tagbilaran',      'Soar to Speed!',                            NOW(), NOW()),
(39, 'Northern Stars', 'NS', '006847', 'A2AAAD', 1, 3, 'Roxas City', 'Shine Unrivaled!',                          NOW(), NOW()),
(40, 'Ninjas',    'NIN', '000000', 'C4CED4', 1, 3, 'Ormoc',           'Strike from Shadows!',                       NOW(), NOW()),
(41, 'Dragons',   'DRA', 'B5121B', 'F7B32B', 1, 3, 'Kalibo',          'Breathe the Fire!',                         NOW(), NOW()),
(42, 'Phoenix',   'PHO', '1D1160', 'E56020', 1, 3, 'Catarman',        'Rise from Ashes!',                          NOW(), NOW()),
(43, 'Sharks',    'SHA', '006D75', 'A2AAAD', 1, 3, 'San Jose',        'Bite to Win!',                              NOW(), NOW()),
(44, 'Giants',    'GNT', '0B2265', 'A71930', 1, 3, 'Baybay',          'Tower Over All!',                           NOW(), NOW()),
(45, 'Fire',      'FRE', '98002E', 'FDB927', 1, 3, 'Maasin',          'Ignite the Fight!',                         NOW(), NOW()),
(46, 'Patriots',  'PAT', '002244', 'C60C30', 1, 3, 'Cadiz',           'Defend the Pride!',                         NOW(), NOW()),
(47, 'Aces',      'ACE', 'B4975A', '000000', 1, 3, 'Bogo',            'Ace the Game!',                             NOW(), NOW()),
(48, 'Monsters',  'MNT', '6F263D', 'FDBB30', 1, 3, 'Guihulngan',      'Unleash the Beast!',                        NOW(), NOW()),
(73, 'Storms',    'STM', '0000FF', 'B0C4DE', 1, 3, 'Sipalay',         'Unleash the Tempest!',                      NOW(), NOW()),
(74, 'Elites',    'ECE', '8B0000', '000000', 1, 3, 'Escalante',       'Rise to Excellence!',                       NOW(), NOW()),
(75, 'Sky Express', 'SSE', '1E90FF', 'ADD8E6', 1, 3, 'Silay',         'Soar to Victory!',                          NOW(), NOW()),
(76, 'Ravens',    'MAN', '000000', '800080', 1, 3, 'Mandaue',         'Strike with Stealth!',                      NOW(), NOW()),
-- Conference 4 (Mindanao)
(49, 'Pirates',   'PIR', 'FFB612', '34302B', 1, 4, 'Davao City',      'Plunder the Prize!',                        NOW(), NOW()),
(50, 'Scorpions', 'SCR', '8A4F00', 'FFD700', 1, 4, 'Zamboanga',       'Sting with Force!',                         NOW(), NOW()),
(51, 'Golds',     'CDO', 'FFD700', '000000', 1, 4, 'Cagayan de Oro',  'Crush the Rivals!',                         NOW(), NOW()),
(52, 'Reapers',   'RPR', '1B1B1B', 'D50000', 1, 4, 'General Santos',  'Harvest the Win!',                          NOW(), NOW()),
(53, 'Raiders',   'RAI', '000000', 'A5ACAF', 1, 4, 'Butuan',          'Seize the Victory!',                        NOW(), NOW()),
(54, 'Whales',    'WH',  '005C5C', 'A1D6E2', 1, 4, 'Tagum',           'Dive to Dominate!',                         NOW(), NOW()),
(55, 'Poseidons', 'POS', '003B4F', '00B4D8', 1, 4, 'Surigao City',    'Command the Tides!',                        NOW(), NOW()),
(56, 'Cyclones',  'CYC', '4B0082', 'FFD700', 1, 4, 'Cotabato City',   'Spin to Glory!',                            NOW(), NOW()),
(57, 'Force',     'ZDF', '006BB6', 'ED174C', 1, 4, 'Zamboanga del Sur', 'Charge with Power!',                      NOW(), NOW()),
(58, 'Astronauts', 'AST', '1A1A40', 'F28C28', 1, 4, 'Lanao del Sur',   'Orbit to Victory!',                         NOW(), NOW()),
(59, 'Demons',    'DMN', '0B162A', 'FF3C00', 1, 4, 'Iligan City',     'Unleash the Chaos!',                        NOW(), NOW()),
(60, 'Devils',    'DVL', 'D50A0A', '000000', 1, 4, 'Malaybalay',      'Burn with Passion!',                        NOW(), NOW()),
(61, 'Bulldogs',  'BD',  '003087', 'A3A3A3', 1, 4, 'Kidapawan',       'Bark and Bite!',                            NOW(), NOW()),
(62, 'Hornets',   'HRN', '1C2526', '00B2A9', 1, 4, 'Davao del Sur',   'Buzz to Victory!',                          NOW(), NOW()),
(63, 'Rebels',    'RBL', 'EF0107', '1E1E2F', 1, 4, 'Davao del Norte', 'Defy and Conquer!',                         NOW(), NOW()),
(64, 'Owls',      'OWL', '0C2340', 'C8102E', 1, 4, 'Surigao del Norte', 'Hunt by Night!',                         NOW(), NOW()),
(77, 'Marlins',   'MRL', '4682B4', 'FF69B4', 1, 4, 'Koronadal',       'Swim to Triumph!',                          NOW(), NOW()),
(78, 'Black Bulls', 'BBB', '000000', 'B8860B', 1, 4, 'Basilan',       'Charge with Force!',                        NOW(), NOW()),
(79, 'Steels',    'SLU', '4682B4', 'A9A9A9', 1, 4, 'Sulu',            'Forge the Win!',                            NOW(), NOW()),
(80, 'Cobras',    'VLC', '006400', 'FFD700', 1, 4, 'Valencia',        'Strike with Precision!',                     NOW(), NOW());